API_KEY_ID = "PK5BV8VUND4Z9XDVZKHD"
API_KEY = "PK5BV8VUND4Z9XDVZKHD"
SECRET_KEY = "MOoOav9zW8e9fu7Hol0XFc33aGv8NAMzh71R18R8"
APCA_API_KEY_ID = "PK5BV8VUND4Z9XDVZKHD"
APCA_SECRET_KEY = "MOoOav9zW8e9fu7Hol0XFc33aGv8NAMzh71R18R8"
api_key = API_KEY_ID
api_secret = SECRET_KEY
HEADERS = {
    'APCA-API-KEY-ID': API_KEY,
    'APCA-API-SECRET-KEY': SECRET_KEY
}
BARS_URL = 'https://data.alpaca.markets/v1/bars'