API_KEY_ID = "PKQP95694TAKTT9BD5VK"
SECRET_KEY = "hIrn8xG5zeUsKQbOa1iF6zcYsrhxjOghsHwOsgdB"
APCA_API_KEY_ID = "PKQP95694TAKTT9BD5VK"
APCA_SECRET_KEY = "hIrn8xG5zeUsKQbOa1iF6zcYsrhxjOghsHwOsgdB"
api_key = API_KEY_ID
api_secret = SECRET_KEY
