API_KEY_ID = "PKLTVC6TY6ERYKKY56DH"
API_KEY = "PKLTVC6TY6ERYKKY56DH"
SECRET_KEY = "EaVqvNyPfxUENzfEwv4JKmhIkIj09p4l6G3BGHuB"
APCA_API_KEY_ID = "PKLTVC6TY6ERYKKY56DH"
APCA_SECRET_KEY = "EaVqvNyPfxUENzfEwv4JKmhIkIj09p4l6G3BGHuB"
api_key = API_KEY_ID
api_secret = SECRET_KEY
HEADERS = {
    'APCA-API-KEY-ID': API_KEY,
    'APCA-API-SECRET-KEY': SECRET_KEY
}
BARS_URL = 'https://data.alpaca.markets/v1/bars'